sudo: required
language: go

before_install:
  - sudo apt-get update
  - sudo apt-get install -y make libx11-dev libxtst-dev libgtk-3-dev

install:
  - make build
  - bash osc.bash

script:
  - echo END
